[package]
name = "with_crc_derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = ["extra-traits", "full", "visit-mut"] }
quote = "1"
